services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: "1000:998"  # Keeps your Docker socket group access fully authorized
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Kept for container api tracking
    restart: unless-stopped
