services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: "1000:998"  # Maps your Ubuntu user and the correct local Docker socket GID
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/host/rootfs:ro
    restart: unless-stopped
