---
- Documentation:
    - Docker:
        - abbr: DK
          href: https://docs.docker.com

    - Grafana:
        - abbr: GF
          href: https://grafana.com/docs

    - Prometheus:
        - abbr: PM
          href: https://prometheus.io/docs

    - Arch Wiki:
        - abbr: AW
          href: https://wiki.archlinux.org

- Development:
    - GitHub:
        - abbr: GH
          href: https://github.com

    - AWS:
        - abbr: AWS
          href: https://console.aws.amazon.com

    - Terraform:
        - abbr: TF
          href: https://developer.hashicorp.com/terraform

- Community:
    - Reddit Homelab:
        - abbr: RH
          href: https://reddit.com/r/homelab

    - Reddit SelfHosted:
        - abbr: SH
          href: https://reddit.com/r/selfhosted
