- logo:
    icon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/icons/homepage.png

- datetime:
    text_color: "slate"
    format:
      date_style: "short"
      time_style: "short"
      hour12: true

- resources:
    cpu: true
    memory: true
    disk: /
